### ISSUE TITLE
Lagopus switch with Ryu controller firewall application

### ISSUE THREAD

**Issue by LucasShih** [lagopus/lagopus#76] opened 2016-04-18 13:33 UTC
Hello, I found a problem that Lagopus switch with Ryu controller firewall application.

Lagopus version is 0.2.5
DPDK version is 2.2.0
Ryu controller execute ryu-manager ryu.app.rest_firewall 

I want to two PCs connected Lagopus switch can ping each other, the flow entry and the controller message are as below:
 
**Ryu controller:**
>curl http://localhost:8080/firewall/rules/25a6024a363e7de6
[{"access_control_list": [{"rules": [{"priority": 1, "dl_type": "IPv4", "nw_proto": "ICMP", "nw_dst": "10.1.1.1/255.255.255.255", "nw_src": "10.1.1.2/255.255.255.255", "rule_id": 1, "actions": "DENY"}, {"priority": 1, "dl_type": "IPv4", "nw_proto": "ICMP", "nw_dst": "10.1.1.2/255.255.255.255", "nw_src": "10.1.1.1/255.255.255.255", "rule_id": 2, "actions": "DENY"}]}], "switch_id": "25a6024a363e7de6"}]

**Lagopus**
>sudo lagosh
>show flowBridge: br0
 Table id: 0
priority=65534,idle_timeout=0,hard_timeout=0,flags=0,cookie=0,packet_count=3,byte_count=180,arp actions=output:normal
 
priority=1,idle_timeout=0,hard_timeout=0,flags=0,cookie=1,packet_count=0,byte_count=0,ip,ip_proto=1,ipv4_src=10.1.1.2/0xffffffff,ipv4_dst=10.1.1.1/0xffffffff actions=output:normal

priority=1,idle_timeout=0,hard_timeout=0,flags=0,cookie=2,packet_count=0,byte_count=0,ip,ip_proto=1,ipv4_src=10.1.1.1/0xffffffff,ipv4_dst=10.1.1.2/0xffffffff actions=output:normal

priority=0,idle_timeout=0,hard_timeout=0,flags=0,cookie=0,packet_count=46,byte_count=5220 actions=output:controller

In Ryu controller, the actions are DENY, but in lagopus switch flow entries actions are normal
Is there have any method to solve it ?  THANK YOU!

**Comment by ynkjm** [comment] 2016-04-19 11:51
Hi @LucasShih,

Your output seems that you used the old version of lagosh (0.1.2?).
Could you check with lagopus 0.2.5 and the latest version of lagosh?

We run the same application on the same version with raw-socket mode.
It worked well with the following output:

```
% curl -X POST -d  '{"nw_src": "10.0.0.2/32", "nw_dst": "10.0.0.3/32", "nw_proto": "ICMP", "actions": "DENY", "priority": "10"}' http://localhost:8080/firewall/rules/0000000000000001
[{"switch_id": "0000000000000001", "command_result": [{"result": "success", "details": "Rule added. : rule_id=1"}]}]
% curl  http://localhost:8080/firewall/rules/0000000000000001[{"access_control_list": [{"rules": [{"priority": 10, "dl_type": "IPv4", "nw_proto": "ICMP", "nw_dst": "10.0.0.3/255.255.255.255", "nw_src": "10.0.0.2/255.255.255.255", "rule_id": 1, "actions": "DENY"}]}], "switch_id": "0000000000000001"}]
% ./test/datastore/tools/check_cmd.py
> flow
{"ret":"OK",
"data":[{"name":":bridge01",
"tables":[{"table":0,
"flows":[{"priority":65535,
"idle_timeout":0,
"hard_timeout":0,
"cookie":0,
"actions":[]},
{"priority":65534,
"idle_timeout":0,
"hard_timeout":0,
"cookie":0,
"dl_type":"arp",
"actions":[{"apply_actions":
[{"output":"normal"}]}]},
{"priority":10,
"idle_timeout":0,
"hard_timeout":0,
"cookie":1,
"dl_type":"ip",
"nw_proto":1,
"nw_src":"10.0.0.2\/255.255.255.255",
"nw_dst":"10.0.0.3\/255.255.255.255",
"actions":[{"apply_actions":
[{"output":"controller"}]}]},
{"priority":0,
"idle_timeout":0,
"hard_timeout":0,
"cookie":0,
"actions":[{"apply_actions":
[{"output":"controller"}]}]}]}]}]}
```

**Comment by LucasShih** [comment] 2016-04-19 13:47
Sorry I have not illustrate clearly.

On Ryu controller, I execute these command as below:
  curl -X PUT http://localhost:8080/firewall/module/enable/0000000000000001
  curl -X POST -d '{"nw_src ": "10.1.1.1/32" , "nw_dst ": "10.1.1.2/32" ,"nw_proto ": "ICMP", "actions": "ALLOW"}' http://localhost:8080/firewall/rules/0000000000000001
  curl -X POST -d '{"nw_src ": "10.1.1.2/32" , "nw_dst ": "10.1.1.1/32" ,"nw_proto ": "ICMP", "actions": "ALLOW"}' http://localhost:8080/firewall/rules/0000000000000001
  
  I wanted to the two PCs(10.1.1.1 and 10.1.1.2) can ping each other

But when I check the rules on controller the actions were shown DENY:
  curl http://localhost:8080/firewall/rules/0000000000000001
  [{"access_control_list": [{"rules": [{"priority": 1, "dl_type": "IPv4", "nw_proto": "ICMP", "nw_dst": "10.1.1.2/255.255.255.255", "nw_src": "10.1.1.1/255.255.255.255", "rule_id": 1, "actions": "DENY"}, {"priority": 1, "dl_type": "IPv4", "nw_proto": "ICMP", "nw_dst": "10.1.1.1/255.255.255.255", "nw_src": "10.1.1.2/255.255.255.255", "rule_id": 2, "actions": "DENY"}]}], "switch_id": "0000000000000001"}]

And the lagopus switch flow entries were right as below:

Lagosh> show flow
[
    {
        "tables": [
            {
                "table": 0, 
                "flows": [
                    {
                        "dl_type": "arp", 
                        "stats": {
                            "packet_count": 752, 
                            "byte_count": 45120
                        }, 
                        "hard_timeout": 0, 
                        "actions": [
                            {
                                "apply_actions": [
                                    {
                                        "output": "normal"
                                    }
                                ]
                            }
                        ], 
                        "priority": 65534, 
                        "idle_timeout": 0, 
                        "cookie": 0
                    }, 
                    {
                        "dl_type": "ip", 
                        "stats": {
                            "packet_count": 0, 
                            "byte_count": 0
                        }, 
                        "hard_timeout": 0, 
                        "nw_dst": "10.1.1.2/255.255.255.255", 
                        "nw_proto": 1, 
                        "actions": [
                            {
                                "apply_actions": [
                                    {
                                        "output": "normal"
                                    }
                                ]
                            }
                        ], 
                        "priority": 1, 
                        "idle_timeout": 0, 
                        "cookie": 1, 
                        "nw_src": "10.1.1.1/255.255.255.255"
                    }, 
                    {
                        "dl_type": "ip", 
                        "stats": {
                            "packet_count": 0, 
                            "byte_count": 0
                        }, 
                        "hard_timeout": 0, 
                        "nw_dst": "10.1.1.1/255.255.255.255", 
                        "nw_proto": 1, 
                        "actions": [
                            {
                                "apply_actions": [
                                    {
                                        "output": "normal"
                                    }
                                ]
                            }
                        ], 
                        "priority": 1, 
                        "idle_timeout": 0, 
                        "cookie": 2, 
                        "nw_src": "10.1.1.2/255.255.255.255"
                    }, 
                    {
                        "stats": {
                            "packet_count": 46, 
                            "byte_count": 6755
                        }, 
                        "hard_timeout": 0, 
                        "actions": [
                            {
                                "apply_actions": [
                                    {
                                        "output": "controller"
                                    }
                                ]
                            }
                        ], 
                        "priority": 0, 
                        "idle_timeout": 0, 
                        "cookie": 0
                    }
                ]
            }
        ], 
        "name": "bridge1", 
        "is-enabled": true
    }
]


I tested Lagopus version both 0.2.5 and 0.1.2, the situation were same, two PCs could not ping each other.

**Comment by ynkjm** [comment] 2016-04-22 09:16
Hi,

We found that the issue you have reported is caused by ryu's bug.
in ``to_rest method()``, Ryu script compares the string value of ``NORMAL`` and the integer value of OpenFlow NORMAL port (``OFPP_NORMAL = 0xfffffffa``).

ryu/app/rest_firewall.py
```    @staticmethod
    def to_rest(dp, openflow):
        if REST_ACTION in openflow:
            action_allow = 'OUTPUT:%d' % dp.ofproto.OFPP_NORMAL
            if openflow[REST_ACTION] == [action_allow]: 
                action = {REST_ACTION: REST_ACTION_ALLOW}
            else:
                action = {REST_ACTION: REST_ACTION_DENY}
        else:
            action = {REST_ACTION: 'Unknown action type.'}

        return action
```

In addition, Lagopus will drops a packet when hybrid mode is not enabled in the build configuretion phase (configure option) and NORMAL port is specified in OpenFlow output action. 
If you want to enable OFPP_NORMAL  in lagopus, please specify ``--enable-hybrid`` in configure. 

Thanks,

**Comment by LucasShih** [comment] 2016-04-22 16:06
Thank you, that is useful.

**Comment by ynkjm** [comment] 2016-04-25 12:47
Hi @LucasShih,

Great, we close this issue.

Thanks!

**Closed by ynkjm** 2016-04-25 12:47 UTC
Labels: Under investigation

**Comment by Hong-Panha** [comment] 2016-08-03 05:04
I am sorry but can anyone tell me how to specify "--enable-hybrid" in lagopus configure ?  I am using lagosh to config the lagopus.

**Comment by ynkjm** [comment] 2016-08-03 05:20
Hi @Hong-Panha 

Your question is not related issues, so could you create another issue if you have any future question?
The hybrid option of "--enable-hybrid" is configured by `configure` at the Lagopus installation steps.

**Comment by Hong-Panha** [comment] 2016-08-03 05:29
Hi @ynkjm 

Actually i had the same problem as @LucasShih. I am trying to implement firewall on Lagopus. I run rest_firewall.py through ryu-manager just like @LucasShih did. But it didn't work. And i read this issue and saw you suggested the solutions but i am wonder how can i specify that. I installed lagopus following the QUICKSTART.md.

**Comment by ynkjm** [comment] 2016-08-03 05:33
Hi @Hong-Panha ,

Would you give us issue details that you face?

**Comment by Hong-Panha** [comment] 2016-08-03 05:49
I am using Lagopus as my open flow switch and i connect two pcs to the switch. Even I set the rule to give the permission for the packet but i still cannot ping. Please refer to the attachment file which consist of log from ryu- manager and rules of firewall.

![screen shot 2016-07-21 at 5 11 06 pm](https://cloud.githubusercontent.com/assets/20162688/17355140/64b9c420-5989-11e6-94a0-fab5e43c6796.png)
![screen shot 2016-07-21 at 5 05 09 pm](https://cloud.githubusercontent.com/assets/20162688/17355144/6c04f196-5989-11e6-835a-33699e6cbada.png)
![screen shot 2016-07-21 at 5 08 29 pm](https://cloud.githubusercontent.com/assets/20162688/17355146/6c45d5ee-5989-11e6-9bc4-02c7e9266776.png)

**Comment by iwaseyusuke** [comment] 2016-08-18 01:30
Excuse me for cutting in,

I wonder if "--enable-hybrid" is available with the non-DPDK version which specified with "--disable-dpdk" option.
On my environment, I'm using Mininet, so I can only use non-DPDK version.

With './configure --disable-dpdk --enable-hybrid=yes', the "output": "normal" action does not seem to work well.

Should "--enable-hybrid" be used with the DPDK version?

**Comment by ynkjm** [comment] 2016-08-26 04:11
@Hong-Panha,

Sorry for late reply.
Could you show us the flow entry and your configuration of Lagopus switch?

**Comment by Hong-Panha** [comment] 2016-08-31 10:43
Hi @ynkjm 

Sorry for late response.

Here is the Lagopus Configuration and i will send the flow entry later when i do the experiment again cause i am on my vacation. I cannot access the lab. 

PS: I haven't reinstall Lagopus with the "--enable-hybrid" yet.

interface {
        interface01 {
                type ethernet-dpdk-phy;
                port-number 0;
                mtu 1500;
                ip-addr 127.0.0.1;
        }
        interface02 {
                type ethernet-dpdk-phy;
                port-number 1;
                mtu 1500;
                ip-addr 127.0.0.1;
        }
        interface03 {
                type ethernet-dpdk-phy;
                port-number 2;
                mtu 1500;
                ip-addr 127.0.0.1;
        }
}
port {
        port01 {
                interface interface01;
        }
        port02 {
                interface interface02;
        }
        port03 {
                interface interface03;
        }
}
channel {
        channel01 {
                dst-addr 127.0.0.1;
                dst-port 6633;
    	        local-addr 0.0.0.0;
                local-port 0;
                protocol tcp;
        }
}
controller {
        controller01 {
                channel channel01;
                role equal;
                connection-type main;
        }
}
bridge {
        bridge01 {							
                dpid 1;
                controller controller01;		
                port port01 1;				
                port port02 2;
                port port03 3;
                fail-mode secure;
                flow-statistics true;
                group-statistics true;
                port-statistics true;
                queue-statistics true;
                table-statistics true;
                reassemble-ip-fragments false;
                max-buffered-packets 65535;
                max-ports 255;
                max-tables 255;
                max-flows 4294967295;
                packet-inq-size 1000;
                packet-inq-max-batches 1000;
                up-streamq-size 1000;
                up-streamq-max-batches 1000;
                down-streamq-size 1000;
                down-streamq-max-batches 1000;
                block-looping-ports false;
        }
}
                                                                                                                                                                


Thanks

**Comment by Hong-Panha** [comment] 2016-11-18 12:03
Hi @LucasShih,

I am trying to run Ryu firewall application on Lagopus switch but there are some problems just like you have mentioned above. Even though I have set up the rule to permit ping, i still cannot ping between my two PCs. And i already reinstalled my lagopus to hybrid mode.

I hope you can share some of your experience related to this issue.

Best Regards,
Panha
